import comp from "F:/桌面/【Vue】/Blog/keano/.vscode/.vp-temp/pages/study/coding/JS/一些常用的方法.html.vue"
const data = JSON.parse("{\"path\":\"/study/coding/JS/%E4%B8%80%E4%BA%9B%E5%B8%B8%E7%94%A8%E7%9A%84%E6%96%B9%E6%B3%95.html\",\"title\":\"1 对象的方法（object method）\",\"lang\":\"zh-CN\",\"frontmatter\":{\"number headings\":\"auto, first-level 1, max 6, contents ^top, 1.1\",\"description\":\"1 对象的方法（object method） 2 数组的方法(Array Method)\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://situ-bei.github.io/keano/keano/study/coding/JS/%E4%B8%80%E4%BA%9B%E5%B8%B8%E7%94%A8%E7%9A%84%E6%96%B9%E6%B3%95.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"KEANO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"1 对象的方法（object method）\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1 对象的方法（object method） 2 数组的方法(Array Method)\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"1 对象的方法（object method）\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Keano\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[],\"git\":{\"createdTime\":null,\"updatedTime\":null,\"contributors\":[]},\"readingTime\":{\"minutes\":6.41,\"words\":1924},\"filePathRelative\":\"study/coding/JS/一些常用的方法.md\",\"excerpt\":\"\\n<h1>2 数组的方法(Array Method)</h1>\\n<div class=\\\"language- line-numbers-mode\\\" data-highlighter=\\\"shiki\\\" data-ext=\\\"\\\" data-title=\\\"\\\" style=\\\"--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34\\\"><pre class=\\\"shiki shiki-themes one-light one-dark-pro vp-code\\\"><code><span class=\\\"line\\\"><span># Array.Prototype.toString()</span></span>\\n<span class=\\\"line\\\"><span>可以将数组转换成字符串</span></span>\\n<span class=\\\"line\\\"><span></span></span>\\n<span class=\\\"line\\\"><span>const a = [1,2,3,4,5]</span></span>\\n<span class=\\\"line\\\"><span>const a = [[[1,[2,3],4],5]]//对于嵌套数组依然可用</span></span>\\n<span class=\\\"line\\\"><span>console.log(a.toString.call(a));//\\\"1,2,3,4,5\\\"</span></span>\\n<span class=\\\"line\\\"><span>console.log(a.toString(a));//\\\"1,2,3,4,5\\\"</span></span>\\n<span class=\\\"line\\\"><span>console.log(Object.prototype.toString.call(a));//[object Array]</span></span></code></pre>\\n<div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\" style=\\\"counter-reset:line-number 0\\\"><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
