import comp from "F:/桌面/【Vue】/Blog/keano/.vscode/.vp-temp/pages/study/coding/HTML/HTML4基础知识.html.vue"
const data = JSON.parse("{\"path\":\"/study/coding/HTML/HTML4%E5%9F%BA%E7%A1%80%E7%9F%A5%E8%AF%86.html\",\"title\":\"《HTML4》\",\"lang\":\"zh-CN\",\"frontmatter\":{\"number headings\":\"auto, first-level 1, max 6, 1.1\",\"title\":\"《HTML4》\",\"category\":[\"前端\",\"HTML\"],\"tags\":[\"HTML\",\"HTML4\"],\"article\":false,\"date\":\"2024-06-24T00:00:00.000Z\",\"feed\":false,\"seo\":false,\"head\":[]},\"headers\":[{\"level\":2,\"title\":\"1 HTML 注释\",\"slug\":\"_1-html-注释\",\"link\":\"#_1-html-注释\",\"children\":[]},{\"level\":2,\"title\":\"2 HTML 文档声明\",\"slug\":\"_2-html-文档声明\",\"link\":\"#_2-html-文档声明\",\"children\":[]},{\"level\":2,\"title\":\"3 HTML 字符编码\",\"slug\":\"_3-html-字符编码\",\"link\":\"#_3-html-字符编码\",\"children\":[]},{\"level\":2,\"title\":\"4 HTML 设置语言\",\"slug\":\"_4-html-设置语言\",\"link\":\"#_4-html-设置语言\",\"children\":[]},{\"level\":2,\"title\":\"5 HTML 4基础\",\"slug\":\"_5-html-4基础\",\"link\":\"#_5-html-4基础\",\"children\":[{\"level\":3,\"title\":\"5.1 排版标签\",\"slug\":\"_5-1-排版标签\",\"link\":\"#_5-1-排版标签\",\"children\":[]},{\"level\":3,\"title\":\"5.2 语义化标签\",\"slug\":\"_5-2-语义化标签\",\"link\":\"#_5-2-语义化标签\",\"children\":[]},{\"level\":3,\"title\":\"5.3 块级元素 与 行内元素\",\"slug\":\"_5-3-块级元素-与-行内元素\",\"link\":\"#_5-3-块级元素-与-行内元素\",\"children\":[]},{\"level\":3,\"title\":\"5.4 文本标签_常用的\",\"slug\":\"_5-4-文本标签-常用的\",\"link\":\"#_5-4-文本标签-常用的\",\"children\":[]},{\"level\":3,\"title\":\"5.5 文本标签_不常用的\",\"slug\":\"_5-5-文本标签-不常用的\",\"link\":\"#_5-5-文本标签-不常用的\",\"children\":[]},{\"level\":3,\"title\":\"5.6 图片标签\",\"slug\":\"_5-6-图片标签\",\"link\":\"#_5-6-图片标签\",\"children\":[]},{\"level\":3,\"title\":\"5.7 超链接\",\"slug\":\"_5-7-超链接\",\"link\":\"#_5-7-超链接\",\"children\":[]},{\"level\":3,\"title\":\"5.8 列表\",\"slug\":\"_5-8-列表\",\"link\":\"#_5-8-列表\",\"children\":[]},{\"level\":3,\"title\":\"5.9 表格\",\"slug\":\"_5-9-表格\",\"link\":\"#_5-9-表格\",\"children\":[]},{\"level\":3,\"title\":\"5.10 常用标签补充\",\"slug\":\"_5-10-常用标签补充\",\"link\":\"#_5-10-常用标签补充\",\"children\":[]},{\"level\":3,\"title\":\"5.11 表单\",\"slug\":\"_5-11-表单\",\"link\":\"#_5-11-表单\",\"children\":[]},{\"level\":3,\"title\":\"5.11.2 Type属性\",\"slug\":\"_5-11-2-type属性\",\"link\":\"#_5-11-2-type属性\",\"children\":[]},{\"level\":3,\"title\":\"5.11.3 常用表单控件\",\"slug\":\"_5-11-3-常用表单控件\",\"link\":\"#_5-11-3-常用表单控件\",\"children\":[]},{\"level\":3,\"title\":\"5.12 iframe 框架标签\",\"slug\":\"_5-12-iframe-框架标签\",\"link\":\"#_5-12-iframe-框架标签\",\"children\":[]},{\"level\":3,\"title\":\"5.13 HTML实体\",\"slug\":\"_5-13-html实体\",\"link\":\"#_5-13-html实体\",\"children\":[]},{\"level\":3,\"title\":\"5.14 meta 元信息\",\"slug\":\"_5-14-meta-元信息\",\"link\":\"#_5-14-meta-元信息\",\"children\":[]}]}],\"git\":{\"createdTime\":1728822746000,\"updatedTime\":1729368407000,\"contributors\":[{\"name\":\"situ-bei\",\"email\":\"2606405907@qq.com\",\"commits\":3}]},\"readingTime\":{\"minutes\":18.55,\"words\":5566},\"filePathRelative\":\"study/coding/HTML/HTML4基础知识.md\",\"localizedDate\":\"2024年6月24日\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
