import comp from "F:/桌面/【Vue】/Blog/keano/.vscode/.vp-temp/pages/study/coding/CSS/Less.html.vue"
const data = JSON.parse("{\"path\":\"/study/coding/CSS/Less.html\",\"title\":\"1 注释\",\"lang\":\"zh-CN\",\"frontmatter\":{\"number headings\":\"auto, first-level 1, max 6, contents ^top, 1.1\",\"cssclasses\":[\"前端\"],\"tags\":[\"CSS\",\"Front-end\"],\"date\":\"2024-07-02T02:16:00.000Z\",\"description\":\"1 注释 1.1 单行注释 语法：// 注释内容 快捷键：ctrl + / 1.2 块注释 语法：/* 注释内容 */ 快捷键： Shift + Alt + A 2 运算 加、减、乘直接书写计算表达式 除法需要添加 （） 或 . 表达式存在多个单位以第一个单位为准 3 嵌套 作用：快速生成后代选择器 ![[Pasted image 2024070202...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://situ-bei.github.io/keano/keano/study/coding/CSS/Less.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"KEANO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"1 注释\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1 注释 1.1 单行注释 语法：// 注释内容 快捷键：ctrl + / 1.2 块注释 语法：/* 注释内容 */ 快捷键： Shift + Alt + A 2 运算 加、减、乘直接书写计算表达式 除法需要添加 （） 或 . 表达式存在多个单位以第一个单位为准 3 嵌套 作用：快速生成后代选择器 ![[Pasted image 2024070202...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-13T12:32:26.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"CSS\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Front-end\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-07-02T02:16:00.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-13T12:32:26.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"1 注释\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-07-02T02:16:00.000Z\\\",\\\"dateModified\\\":\\\"2024-10-13T12:32:26.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Keano\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1.1 单行注释\",\"slug\":\"_1-1-单行注释\",\"link\":\"#_1-1-单行注释\",\"children\":[]},{\"level\":2,\"title\":\"1.2 块注释\",\"slug\":\"_1-2-块注释\",\"link\":\"#_1-2-块注释\",\"children\":[]},{\"level\":2,\"title\":\"6.1 禁止导出\",\"slug\":\"_6-1-禁止导出\",\"link\":\"#_6-1-禁止导出\",\"children\":[]}],\"git\":{\"createdTime\":1728589721000,\"updatedTime\":1728822746000,\"contributors\":[{\"name\":\"situ-bei\",\"email\":\"2606405907@qq.com\",\"commits\":2}]},\"readingTime\":{\"minutes\":1.07,\"words\":321},\"filePathRelative\":\"study/coding/CSS/Less.md\",\"localizedDate\":\"2024年7月2日\",\"excerpt\":\"\\n<h2>1.1 单行注释</h2>\\n<ul>\\n<li>语法：<code>//</code> 注释内容</li>\\n<li>快捷键：<code>ctrl + /</code></li>\\n</ul>\\n<h2>1.2 块注释</h2>\\n<p>语法：<code>/*</code> 注释内容 <code>*/</code>\\n快捷键： <code>Shift + Alt + A</code></p>\\n<h1>2 运算</h1>\\n<ul>\\n<li>加、减、乘直接书写计算表达式</li>\\n<li>除法需要添加 <code>（）</code> 或 <code>.</code></li>\\n<li>表达式存在多个单位以第一个单位为准</li>\\n</ul>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
