import comp from "F:/桌面/【Vue】/Blog/keano/.vscode/.vp-temp/pages/study/coding/CSS/移动端布局.html.vue"
const data = JSON.parse("{\"path\":\"/study/coding/CSS/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%B8%83%E5%B1%80.html\",\"title\":\"1 移动端布局的基本概述\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"1 移动端布局的基本概述 1.1 屏幕分辨率 分类： 物理分辨率：硬件分辨率（出厂设置） 逻辑分辨率：软件 / 驱动设置 结论： 制作网页参考 逻辑分辨率 ![[1681811157520.png|400]] 2 vw适配方案 2.1 vw和vh基本使用 vw和vh是相对单位，相对视口尺寸计算结果 vw：viewport width（1vw = 1/1...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://situ-bei.github.io/keano/keano/study/coding/CSS/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E5%B8%83%E5%B1%80.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"KEANO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"1 移动端布局的基本概述\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"1 移动端布局的基本概述 1.1 屏幕分辨率 分类： 物理分辨率：硬件分辨率（出厂设置） 逻辑分辨率：软件 / 驱动设置 结论： 制作网页参考 逻辑分辨率 ![[1681811157520.png|400]] 2 vw适配方案 2.1 vw和vh基本使用 vw和vh是相对单位，相对视口尺寸计算结果 vw：viewport width（1vw = 1/1...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-10T19:48:41.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-10T19:48:41.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"1 移动端布局的基本概述\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":\\\"2024-10-10T19:48:41.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Keano\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"1.1 屏幕分辨率\",\"slug\":\"_1-1-屏幕分辨率\",\"link\":\"#_1-1-屏幕分辨率\",\"children\":[]},{\"level\":2,\"title\":\"2.1 vw和vh基本使用\",\"slug\":\"_2-1-vw和vh基本使用\",\"link\":\"#_2-1-vw和vh基本使用\",\"children\":[]},{\"level\":2,\"title\":\"2.2 vw布局\",\"slug\":\"_2-2-vw布局\",\"link\":\"#_2-2-vw布局\",\"children\":[]},{\"level\":2,\"title\":\"2.3 vh问题\",\"slug\":\"_2-3-vh问题\",\"link\":\"#_2-3-vh问题\",\"children\":[]}],\"git\":{\"createdTime\":1728589721000,\"updatedTime\":1728589721000,\"contributors\":[{\"name\":\"situ-bei\",\"email\":\"2606405907@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":0.55,\"words\":165},\"filePathRelative\":\"study/coding/CSS/移动端布局.md\",\"localizedDate\":\"2024年10月11日\",\"excerpt\":\"\\n<h2>1.1 屏幕分辨率</h2>\\n<ul>\\n<li>分类：\\n<ul>\\n<li>物理分辨率：硬件分辨率（出厂设置）</li>\\n<li>逻辑分辨率：软件 / 驱动设置</li>\\n</ul>\\n</li>\\n<li>结论：</li>\\n</ul>\\n<blockquote>\\n<p>制作网页参考 <strong>逻辑分辨率</strong>\\n![[1681811157520.png|400]]</p>\\n</blockquote>\\n<h1>2 vw适配方案</h1>\\n<h2>2.1 vw和vh基本使用</h2>\\n<ul>\\n<li><code>vw</code>和<code>vh</code>是相对单位，相对视口尺寸计算结果</li>\\n<li><code>vw</code>：<code>viewport width</code>（1vw = 1/100视口宽度 ）</li>\\n<li><code>vh</code>：<code>viewport height</code> ( 1vh = 1/100视口高度 )</li>\\n</ul>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
