import comp from "F:/桌面/【Vue】/Blog/keano/.vscode/.vp-temp/pages/study/wiki/显示技术发展史.html.vue"
const data = JSON.parse("{\"path\":\"/study/wiki/%E6%98%BE%E7%A4%BA%E6%8A%80%E6%9C%AF%E5%8F%91%E5%B1%95%E5%8F%B2.html\",\"title\":\"显示技术发展史\",\"lang\":\"zh-CN\",\"frontmatter\":{\"date\":\"2024-03-29T00:00:00.000Z\",\"category\":[\"百科\"],\"tag\":[\"手机\",\"屏幕\",\"让我们变得更强大\"],\"description\":\"显示技术发展史 RT屏幕的原理是什么？ LCD屏幕的原理是什么？ OLED屏幕的原理是什么？ 为什么早期的LCD屏幕显示效果那么差？ LCD屏幕又是如何逐渐提高显示效果，打平OLED的？ 显示屏幕进化的终点在哪里？ AI对显示技术的提升有什么贡献？ 1.RT屏幕的原理是什么？ CRT显示器是靠电子束逐行扫描荧光屏来实现整个画面的显示。 涂满荧光材料的荧...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://situ-bei.github.io/keano/study/wiki/%E6%98%BE%E7%A4%BA%E6%8A%80%E6%9C%AF%E5%8F%91%E5%B1%95%E5%8F%B2.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"KEANO\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"显示技术发展史\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"显示技术发展史 RT屏幕的原理是什么？ LCD屏幕的原理是什么？ OLED屏幕的原理是什么？ 为什么早期的LCD屏幕显示效果那么差？ LCD屏幕又是如何逐渐提高显示效果，打平OLED的？ 显示屏幕进化的终点在哪里？ AI对显示技术的提升有什么贡献？ 1.RT屏幕的原理是什么？ CRT显示器是靠电子束逐行扫描荧光屏来实现整个画面的显示。 涂满荧光材料的荧...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-10-13T12:32:26.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"手机\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"屏幕\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"让我们变得更强大\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-03-29T00:00:00.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-10-13T12:32:26.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"显示技术发展史\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-03-29T00:00:00.000Z\\\",\\\"dateModified\\\":\\\"2024-10-13T12:32:26.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Keano\\\",\\\"url\\\":\\\"https://situ-bei.github.io/keano/\\\"}]}\"]]},\"headers\":[],\"git\":{\"createdTime\":1728822746000,\"updatedTime\":1728822746000,\"contributors\":[{\"name\":\"situ-bei\",\"email\":\"2606405907@qq.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":3.16,\"words\":949},\"filePathRelative\":\"study/wiki/显示技术发展史.md\",\"localizedDate\":\"2024年3月29日\",\"excerpt\":\"\\n<ul>\\n<li>RT屏幕的原理是什么？</li>\\n<li>LCD屏幕的原理是什么？</li>\\n<li>OLED屏幕的原理是什么？</li>\\n<li>为什么早期的LCD屏幕显示效果那么差？</li>\\n<li>LCD屏幕又是如何逐渐提高显示效果，打平OLED的？</li>\\n<li>显示屏幕进化的终点在哪里？</li>\\n<li>AI对显示技术的提升有什么贡献？</li>\\n</ul>\\n<h4>1.RT屏幕的原理是什么？</h4>\\n<p>CRT显示器是靠电子束逐行扫描荧光屏来实现整个画面的显示。\\n涂满荧光材料的荧光屏。\\n电子枪发出来的电子束。\\n电子束射到荧光材料上，荧光材料就会发光，在荧光屏上产生一个光点，荧光屏上每个像素都有红绿蓝三种荧光材料，在电子束的轰击下产生三种不同颜色的光，电子束的强度不同，发出光的亮度也不同，这些光汇合在一起就形成不同的颜射。电子枪在磁场的作用下，从左上角开始扫描，产生画面，画面在视野中的保留1/24秒，在更短的时间内完成下一幅画面，眼睛不会感到画面的消失，联系成一系类的运动画面。\\n最早的CRT显示器出现于1922年，已经经历了一百年的发展，本世纪达到登峰造极的程度，然后被淘汰。\\n在一些特殊领域还是存在，比如美术。</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
